# Generated by Django 4.1.1 on 2022-10-05 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0004_product_set_as_banner_alter_product_is_documented_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="set_as_top_category",
            field=models.BooleanField(default=False, verbose_name="setAsTopCategory"),
        ),
    ]
