# Generated by Django 4.1.1 on 2022-10-05 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0005_product_set_as_top_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="product_slug",
            field=models.SlugField(blank=True, max_length=256, null=True),
        ),
    ]
