# Generated by Django 4.1.1 on 2022-10-05 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0006_product_product_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="product_name",
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
