# Generated by Django 4.1.1 on 2022-10-04 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="birth_date",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="gender",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="mobile_number",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="source",
        ),
    ]
